### ISSUE TITLE
로깅 시스템 구축

### ISSUE THREAD

**Issue by gimseonjin** [DG-times/server#37]
1. 스프링 시큐리티를 사용하기 때문에 권한이 없는 경우, 로그를 찍을 수 없다. 따라서 권한이 없는 요청도 모두 로그를 남기고 싶기 때문에 Fillter에 Logging Fillter를 구현하고자 한다. < 로그 레벨 info
2. Interceptor 영역에서는 Service 단에 어떤 메소드에 어떤 유저가 사용했는지, 사용 빈도를 체크하는 logging를 하고 싶다. < 로그 레벨 info
3. AOP를 활용해서 StartWatch를 사용해서 메소드별 실행 시간을 log로 남기고 싶다. < 로그 레벨 debug
4. 로그는 모두 파일로 저장하며, 날짜에 따라 파일이 생성됩니다.

**Comment by siyoungoh** [comment]
'1', '3' 은 어디에 활용하려고 하는 건가요?

**Comment by KongSangUk** [comment]
(1)
인터셉터와 필터 간의 차이는 유효한 접근인지 아닌지 유효하지 않은 접근도 체크를 해봐야 할 거 같아서 모든 request는 필터 앞에서 로깅 하도록 하고 싶고 유효한 접근은 뒤에서 인터셉터로 또 따로 로깅하려고 합니다.

그리고 위 이유보다 더 궁극적인 목표는 로깅의 세 가지 종류? 인 필터, 인터셉터 AOP 모두 다뤄보고 싶어서입니다.

활용 : 검색기능

(3)
특정 메소드의 성능을 측정해보고 싶어서 만들려고 합니다.
그리고 log 레벨이 debug인 것은 프로그램 개발할 때 성능 측정용으로 사용할 것이셔 debug로 했습니다.

대표적인 활용 : 뉴스 데이터
