### ISSUE TITLE
exception 설계 및 구축

### ISSUE THREAD

**Issue by gimseonjin** [DG-times/server#38]
1. exception을 보면, 저희 팀은 모두 Runtime Exception을 사용합니다. 그러나 실무에서는 이는 지양되는 코드 스타일입니다. 이 부분을 모드 Custom exception으로 구현해서 바꾸려고 합니다.
2. 예시 new RuntimeException(”msg”) 방식을 new UserNameDuple();
3. 만들어진 Exception은 static을 활용해서 빠르게 동작하게 하려고 합니다.
4. 만든 Custom Exception을 모두 컨벤션 문서로 작성해야 합니다.

**Comment by siyoungoh** [comment]
이 issue 를 어떻게 나누고 작업했는지 나중에 들려주세요. 궁금하네요.

**Comment by AhnSangRok** [comment]
네 알겠습니다. 슬픈이야기가 될 것 같습니다.
