### ISSUE TITLE
뉴스 데이터 수집

### ISSUE THREAD

**Issue by gimseonjin** [DG-times/server#39]
1. 본격적으로 뉴스 api를 사용해서 데이터를 넣으려고 합니다.
2. 네이버, 카카오, 아님 기타 api를 찾아 비교해서 저희 프로젝트에 적절한 api를 선택합니다.
3. api를 분석해서 실제 데이터를 가져오고 이를 nlp를 통해 키워드를 뽑아냅니다.
4. 뽑아낸 키워드를 데이터베이스에 적재합니다.

**Comment by ikohong88** [comment]
1. SpringBoot로 더미데이터 작업을 할려고 했지만, 로직 수정을 통해 하루에 1500건 처리량에서 1만건으로 늘렸지만, 18만건을 처리해야되는부분을 생각하면, 시간이 너무 오래걸려 다른 방안 모색
2. 팀장님과 상의 후 python으로 넘어가서 작업 진행 시도
3. 찾아온 JSON 데이터파일에서 원하는 데이터만 추출하여, 새로운 JSON 파일 생성
4. celery 사용 예정
